### ISSUE TITLE
MACOS Boot screen resolution issue

### ISSUE THREAD

**Issue by kk98** [mrpapersonic/hp-eb-9480m-oc-efi#3]
Hi, one more issue that I have observed, while booting to MACOS the boot screen logo seems a little bit stretched but after the completion of half loading the resolution gets normal. See the screenshots for the first half and for the other half. Original looks seems on the other half.

Stretched Boot Screen Logo: 

![IMG_20220409_140437](https://user-images.githubusercontent.com/16766950/162582761-8fe5328c-5bbd-4dc9-b18a-4227e29f33c7.jpg)

Original Perfect Boot Screen Logo (after half loading):

![IMG_20220409_140534](https://user-images.githubusercontent.com/16766950/162582782-ab3af9b7-18e3-4c29-b524-5d6c6e5c9422.jpg)

**Comment by mrpapersonic** [comment]
Disable CSM in the BIOS (e.g. UEFI, no CSM).
However, this has the side effect of distorting the Apple logo until after half loading (which is unfortunately just an issue with the computer itself, there is no way around this).
